In [5]:
import numpy as np
b = np.array([1, 2, 3, 4, 5, 6])

In [6]:
b

array([1, 2, 3, 4, 5, 6])

In [7]:
b[0]

np.int64(1)

In [8]:
b.shape

(6,)

In [9]:
b.size

6

In [10]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [11]:
np.flip(arr)

array([8, 6, 4, 7, 3, 5, 1, 2])

In [ ]:
a = np.array(45)
print('No of Shape: ',a.shape)
print('No of Dimension: ',a.ndim)
print('Size: ',a.size)