In [5]:
import numpy as np
b = np.array([1, 2, 3, 4, 5, 6])

In [6]:
b

array([1, 2, 3, 4, 5, 6])

In [7]:
b[0]

np.int64(1)

In [8]:
b.shape

(6,)

In [9]:
b.size

6

In [10]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [11]:
np.flip(arr)

array([8, 6, 4, 7, 3, 5, 1, 2])

In [14]:
a = np.array(45)
print('No of Shape: ',a.shape)
print('No of Dimension: ',a.ndim)
print('Len of Shape: ',len(a.shape))
print('Size: ',a.size)

No of Shape:  ()
No of Dimension:  0
Len of Shape:  0
Size:  1


In [17]:
a = np.array([1,2])
print('No of Shape: ',a.shape)
print('No of Dimension: ',a.ndim)
print('Len of Shape: ',len(a.shape))
print('Size: ',a.size)

No of Shape:  (2,)
No of Dimension:  1
Len of Shape:  1
Size:  2


In [19]:
a = np.array([1,2, 3])
print('No of Shape: ',a.shape)
print('No of Dimension: ',a.ndim)
print('Len of Shape: ',len(a.shape))
print('Size: ',a.size)

No of Shape:  (3,)
No of Dimension:  1
Len of Shape:  1
Size:  3


In [21]:
a = np.array([[1,2,3],[1,2,3]])
print('No of Shape: ',a.shape)
print('No of Dimension: ',a.ndim)
print('Len of Shape: ',len(a.shape))
print('Size: ',a.size)

No of Shape:  (2, 3)
No of Dimension:  2
Len of Shape:  2
Size:  6


In [22]:
a.dtype

dtype('int64')

In [29]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [30]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
np.zeros((6,7,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [32]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [33]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [34]:
np.empty(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [35]:
np.empty((5,6))

array([[1.30943180e-311, 1.02271589e-321, 0.00000000e+000,
        0.00000000e+000, 1.42419937e-306, 5.02034658e+175],
       [3.89051347e-033, 2.83423254e-032, 5.40082158e-066,
        1.04890693e-042, 1.93214003e-076, 4.26306507e-096],
       [1.12855837e+277, 8.76730979e+252, 2.59027920e-144,
        3.80985069e+180, 1.14428494e+243, 2.59027907e-144],
       [7.79952704e-143, 1.45139474e+165, 1.73686814e-047,
        2.92867591e-057, 2.42390241e-052, 2.59027907e-144],
       [2.59903818e-144, 6.50092526e-091, 4.08823766e-033,
        7.49837497e-067, 1.11475752e+261, 1.16318408e-028]])

In [36]:
arr = np.array([2,1,3,5,7,9,8])

In [37]:
np.sort(arr)

array([1, 2, 3, 5, 7, 8, 9])

In [38]:
arr = np.array([30,10,20])
np.argsort(arr)

array([1, 2, 0])

In [43]:
arr = np.array([90,98,23,89,12,43,76])
np.partition(arr,5)

array([12, 23, 43, 76, 89, 90, 98])

In [45]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
np.concatenate((a,b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
z = np.array([[9,10]])
np.concatenate((x,y,z))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [51]:
a = np.arange(2,10,2)
a

array([2, 4, 6, 8])

In [52]:
a.reshape(2,2)

array([[2, 4],
       [6, 8]])

In [55]:
a = np.arange(1,7)
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [60]:
arr = np.arange(6)

In [61]:
np.reshape(arr,(3,2))

array([[0, 1],
       [2, 3],
       [4, 5]])

In [62]:
np.reshape(arr,(2,3), order = 'F')

array([[0, 2, 4],
       [1, 3, 5]])

In [64]:
arr = np.arange(6)
np.reshape(arr,(3,2))
np.reshape(arr,(2,3), order = 'C')

array([[0, 1, 2],
       [3, 4, 5]])